# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Splits a text into one or more sentences.
#'
#' @param text A text.
#' @return An array of sentences.
split_sentences <- function(texts) {
    .Call(`_txtlib_split_sentences`, texts)
}

#' Splits a text into one or more words.
#'
#' @param text A text.
#' @return An array of words.
split_words <- function(texts, word_mask = 2147483647L, non_word_mask = 0L, lowercase = FALSE) {
    .Call(`_txtlib_split_words`, texts, word_mask, non_word_mask, lowercase)
}

