# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

unicode_general_categories <- function() {
    .Call('_txtlib_unicode_general_categories', PACKAGE = 'txtlib')
}

create_uax29_vectorizer_pointer <- function(vocabulary, ignored_terms, casing_transformation, case_sensitive_aliases, case_insensitive_aliases, ngrams_size, min_term_length, stemming_language, word_token_categories, non_word_token_categories, locale) {
    .Call('_txtlib_create_uax29_vectorizer_pointer', PACKAGE = 'txtlib', vocabulary, ignored_terms, casing_transformation, case_sensitive_aliases, case_insensitive_aliases, ngrams_size, min_term_length, stemming_language, word_token_categories, non_word_token_categories, locale)
}

tokenize_impl <- function(vectorizer_handle, texts, parallel = FALSE) {
    .Call('_txtlib_tokenize_impl', PACKAGE = 'txtlib', vectorizer_handle, texts, parallel)
}

sentence_tokenize_impl <- function(vectorizer_handle, texts, parallel = FALSE) {
    .Call('_txtlib_sentence_tokenize_impl', PACKAGE = 'txtlib', vectorizer_handle, texts, parallel)
}

vectorize_impl <- function(vectorizer_handle, texts, parallel = FALSE, with_dimnames = TRUE) {
    .Call('_txtlib_vectorize_impl', PACKAGE = 'txtlib', vectorizer_handle, texts, parallel, with_dimnames)
}

sentence_vectorize_impl <- function(vectorizer_handle, texts, parallel = FALSE, with_dimnames = TRUE) {
    .Call('_txtlib_sentence_vectorize_impl', PACKAGE = 'txtlib', vectorizer_handle, texts, parallel, with_dimnames)
}

